"""Initial Migration
Revision ID: 88a097ce0c17
Revises: 
Create Date: 2020-05-17 13:41:00.668949
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a097ce0c17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###